// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SensorProcessing.DataAccess;

#nullable disable

namespace SensorProcessing.DataAccess.Migrations
{
    [DbContext(typeof(SensorProcessingDbContext))]
    [Migration("20260106202719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.Monitoring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MonitoringStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MonitoringStoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringStartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Monitorings");
                });

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MonitoringId")
                        .HasColumnType("uuid");

                    b.Property<int>("SensorType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("MonitoringId", "Timestamp");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.Monitoring", b =>
                {
                    b.HasOne("SensorProcessing.DataAccess.Models.User", null)
                        .WithMany("Monitorings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.Sensor", b =>
                {
                    b.HasOne("SensorProcessing.DataAccess.Models.Monitoring", "Monitoring")
                        .WithMany("SensorData")
                        .HasForeignKey("MonitoringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitoring");
                });

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.Monitoring", b =>
                {
                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("SensorProcessing.DataAccess.Models.User", b =>
                {
                    b.Navigation("Monitorings");
                });
#pragma warning restore 612, 618
        }
    }
}
